apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTRTTTRYOXZxZGVGTTV5S05acGZyRG5zSGZ2SWw2cERLS3plaUt2b2ZTNXVlCk9WWTlMRTlTK2V6dlRaZUdGM3VSR1lRU2RBQitTMEpjeFlOQVY1TStsU1F6aEZXaWlKYzJ4VldNMGlpaG1iWVEKcFNpRWlQVlFVanJOQnRCYWpmSi9UV1BFRHlTYy9sdjUveGhWYlYzM1JuV1l2dWRsZzhmUUJFS2FVMlJBL3dnWgpWR1ZGbDQ1cWNGZlpLWTBpcDJWMHo5Mm1kdGlpYnV6SUp3bHdlQzNGM1FCTUF5RDFsNzd4aHdMU2hHUko3VWFxCm13MGZVSWVONUhhNGhBNmNDQlFNWWZuZWxpVjYyYW9YS1kyM0RmM1NFYmhJQ251LzU4WkZOWXZNN0Ntd25hZFcKRmlEbGkzOTBzT2pYa0JOMmVieDBxVE9YdUVZUUZEZzVYRnRXTTZPSmJRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBTmxMWEdhRHZDZHk2SCtWYlU1NGZ5QkpsUnpCYzN5akFLTHhEY05XbmdrYTV4U2dwY05oCmZKbXB0S1RFN1VSb3lHRkE4UDB3c0dheFZVWElwc3hFYWRwdnZjTmtNWlJLYmR4MTFiTms2b2ZobmRwSlRLMm8KUDlZNGFoM2p3em90dWxHVzM4NUl6SEZjU3c1VCtWNFZ4QzErOWhaT0NiNEJiYzJoM1FkM1ArYlRYa0F0YzhMdQpzMmE5ZllUejFZUXlLSzJ6U3BCL3Rka2NqMW9ObnRNd2M3MEkxdS9KTCtqSDU5NzFMYkdQRG4xcllTT3JEUmo1CmduT0tmYlBVLzNDaU9FaUJOTE1HZENNZy90bmlLcEZFcTJMMXk2OHRhMHNEdGZRNThVcVk2TmJHRFJNMEtnQU0KVFlLeElvWTA2cm5td2ZDbWhlMVNCUVhlandNS2tSbzJwc289Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
